#!/usr/bin/env python3
"""Upload ticket + data files to S3 and execute the ingest_ticket workflow.

Resolves the private S3 bucket and ingest_ticket state machine ARN from the
deployed CloudFormation stack, uploads the local ticket file and all data
files to the correct S3 key prefixes, then fires the Express workflow via
StartSyncExecution and reports the result.

S3 key layout
-------------
  raw/tickets/<ticket_filename>
  raw/data/<data_slug>/<data_file_1>
  raw/data/<data_slug>/<data_file_2>
  ...

The data_slug is derived from the ticket's OBJECT NAME (lowercased,
underscores preserved) unless overridden with --data-slug.

SFN input event
---------------
  {
      "ticket_path": "raw/tickets/<ticket_filename>",
      "data_dir": "raw/data/<data_slug>/",
      "correlation_id": "<auto-generated or user-supplied>"
  }

Usage
-----
  # Photometry ticket — data_dir contains a single CSV
  python tools/run_ingest_ticket.py \\
      tickets/V4739_Sgr_Livingston_optical_Photometry.txt \\
      data/v4739_sgr/

      OR
python run_ingest_ticket.py tickets/V2572_Sgr_Bateson_optical_Photometry.txt data/v2572_Sgr/


  # Spectra ticket — data_dir contains metadata CSV + spectrum CSVs
  python tools/run_ingest_ticket.py \\
      tickets/GQ_Mus_Williams_Optical_Spectra.txt \\
      data/gq_mus/

  # Dry run — upload to S3 but don't execute the workflow
  python tools/run_ingest_ticket.py \\
      tickets/V4739_Sgr.txt data/v4739_sgr/ --upload-only

  # Target the smoke stack instead of production
  python tools/run_ingest_ticket.py \\
      tickets/V4739_Sgr.txt data/v4739_sgr/ --stack NovaCatSmoke

  # Override the data slug (S3 prefix component)
  python tools/run_ingest_ticket.py \\
      tickets/V4739_Sgr.txt data/v4739_sgr/ --data-slug my_custom_prefix

  # Supply a correlation ID for traceability
  python tools/run_ingest_ticket.py \\
      tickets/V4739_Sgr.txt data/v4739_sgr/ --correlation-id my-run-001

Prerequisites
-------------
  AWS credentials configured (env vars, ~/.aws/credentials, or instance role).
  The target stack must be in CREATE_COMPLETE or UPDATE_COMPLETE.
  boto3 installed (pip install boto3).

Operator tooling — no CI requirements (mypy / ruff not enforced).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from pathlib import Path
from typing import Any

import boto3

# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------


class _C:
    HEADER = "\033[95m"
    BLUE = "\033[94m"
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    END = "\033[0m"


def _banner(text: str) -> None:
    width = max(60, len(text) + 4)
    print(f"\n{_C.BOLD}{_C.CYAN}{'=' * width}{_C.END}")
    print(f"{_C.BOLD}{_C.CYAN}  {text}{_C.END}")
    print(f"{_C.BOLD}{_C.CYAN}{'=' * width}{_C.END}")


def _section(text: str) -> None:
    print(f"\n{_C.BOLD}{_C.BLUE}-- {text} {'-' * max(0, 56 - len(text))}{_C.END}")


def _ok(text: str) -> None:
    print(f"  {_C.GREEN}OK{_C.END} {text}")


def _warn(text: str) -> None:
    print(f"  {_C.YELLOW}!!{_C.END} {text}")


def _err(text: str) -> None:
    print(f"  {_C.RED}XX{_C.END} {text}")


def _info(label: str, value: Any) -> None:
    print(f"  {_C.DIM}{label}:{_C.END} {value}")


def _die(msg: str) -> None:
    _err(msg)
    sys.exit(1)


# ---------------------------------------------------------------------------
# CloudFormation resolution
# ---------------------------------------------------------------------------


def _resolve_stack_outputs(stack_name: str) -> dict[str, str]:
    """Return a dict of export_name -> output_value from the named stack."""
    cf = boto3.client("cloudformation")
    try:
        resp = cf.describe_stacks(StackName=stack_name)
    except Exception as exc:
        _die(f"Cannot describe stack '{stack_name}': {exc}")

    stacks = resp.get("Stacks", [])
    if not stacks:
        _die(f"Stack '{stack_name}' returned no results.")

    status = stacks[0].get("StackStatus", "")
    if status not in {"CREATE_COMPLETE", "UPDATE_COMPLETE"}:
        _die(
            f"Stack '{stack_name}' is in status '{status}' — expected CREATE_COMPLETE or UPDATE_COMPLETE."
        )

    outputs: dict[str, str] = {}
    for output in stacks[0].get("Outputs", []):
        export_name = output.get("ExportName")
        if export_name:
            outputs[export_name] = output["OutputValue"]
    return outputs


def _get_output(outputs: dict[str, str], cf_prefix: str, key: str) -> str:
    """Extract a specific output from the resolved map, or die."""
    export_name = f"{cf_prefix}-{key}"
    val = outputs.get(export_name)
    if not val:
        _die(
            f"Stack is missing export '{export_name}'. "
            "Re-deploy the stack and ensure all CfnOutputs are present."
        )
    return val  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Ticket sniffing — extract OBJECT NAME for the data slug
# ---------------------------------------------------------------------------


def _sniff_object_name(ticket_path: Path) -> str | None:
    """Read the ticket file and extract OBJECT NAME if present."""
    try:
        for line in ticket_path.read_text(encoding="utf-8").splitlines():
            if ":" in line:
                key, _, value = line.partition(":")
                if key.strip().upper() == "OBJECT NAME":
                    return value.strip()
    except Exception:
        pass
    return None


def _slugify(object_name: str) -> str:
    """Convert an object name to a safe S3 prefix slug.

    Lowercases, replaces spaces with underscores, strips anything that
    isn't alphanumeric, underscore, or hyphen.
    """
    slug = object_name.lower().replace(" ", "_")
    slug = re.sub(r"[^a-z0-9_\-]", "", slug)
    return slug


# ---------------------------------------------------------------------------
# S3 upload
# ---------------------------------------------------------------------------


def _upload_files(
    s3: Any,
    bucket: str,
    ticket_path: Path,
    data_dir: Path,
    data_slug: str,
    dry_run: bool = False,
) -> tuple[str, str]:
    """Upload ticket + data files, return (ticket_s3_key, data_dir_s3_prefix)."""
    ticket_s3_key = f"raw/tickets/{ticket_path.name}"
    data_dir_prefix = f"raw/data/{data_slug}/"

    _section("S3 Upload")
    _info("bucket", bucket)
    _info("ticket_key", ticket_s3_key)
    _info("data_prefix", data_dir_prefix)

    # --- Ticket ---
    _upload_one(s3, bucket, ticket_s3_key, ticket_path.read_bytes(), dry_run)

    # --- Data files ---
    data_files = sorted(f for f in data_dir.iterdir() if f.is_file())
    if not data_files:
        _die(f"No files found in data directory: {data_dir}")

    _info("data_files", len(data_files))
    for f in data_files:
        key = f"{data_dir_prefix}{f.name}"
        _upload_one(s3, bucket, key, f.read_bytes(), dry_run)

    return ticket_s3_key, data_dir_prefix


def _upload_one(s3: Any, bucket: str, key: str, body: bytes, dry_run: bool) -> None:
    size_kb = len(body) / 1024
    label = f"s3://{bucket}/{key} ({size_kb:.1f} KB)"
    if dry_run:
        _ok(f"[dry-run] {label}")
    else:
        s3.put_object(Bucket=bucket, Key=key, Body=body)
        _ok(label)


# ---------------------------------------------------------------------------
# SFN execution
# ---------------------------------------------------------------------------


def _execute_workflow(
    sfn: Any,
    state_machine_arn: str,
    ticket_s3_key: str,
    data_dir_prefix: str,
    correlation_id: str,
) -> dict[str, Any]:
    """Fire the Express workflow synchronously and return the response."""
    payload = {
        "ticket_path": ticket_s3_key,
        "data_dir": data_dir_prefix,
        "correlation_id": correlation_id,
    }

    sm_short = state_machine_arn.split(":")[-1][:30]
    execution_name = f"op-{sm_short}-{correlation_id[:20]}"
    # SFN execution names: alphanumeric, hyphens, underscores only
    execution_name = re.sub(r"[^a-zA-Z0-9_\-]", "-", execution_name)[:80]

    _section("Workflow Execution")
    _info("state_machine", state_machine_arn.split(":")[-1])
    _info("execution_name", execution_name)
    _info("correlation_id", correlation_id)
    print(f"\n  {_C.DIM}Input payload:{_C.END}")
    print(f"  {json.dumps(payload, indent=2)}")
    print()

    resp = sfn.start_sync_execution(
        stateMachineArn=state_machine_arn,
        name=execution_name,
        input=json.dumps(payload),
    )
    return resp


def _report_result(resp: dict[str, Any]) -> None:
    """Pretty-print the SFN execution result."""
    status = resp.get("status", "UNKNOWN")

    _section("Execution Result")

    if status == "SUCCEEDED":
        _ok(f"Status: {_C.BOLD}{_C.GREEN}{status}{_C.END}")
    elif status == "FAILED":
        _err(f"Status: {_C.BOLD}{_C.RED}{status}{_C.END}")
    else:
        _warn(f"Status: {_C.BOLD}{_C.YELLOW}{status}{_C.END}")

    # Duration
    start = resp.get("startDate")
    stop = resp.get("stopDate")
    if start and stop:
        duration = (stop - start).total_seconds()
        _info("duration", f"{duration:.1f}s")

    # Output
    raw_output = resp.get("output")
    if raw_output:
        try:
            out = json.loads(raw_output)
            print(f"\n  {_C.DIM}Execution output:{_C.END}")
            print(_indent_json(out))

            # Pull out key summary fields
            _section("Summary")
            _extract_summary(out)

        except json.JSONDecodeError:
            print(f"\n  {_C.DIM}Raw output:{_C.END}")
            print(f"  {raw_output[:2000]}")

    # Error / Cause (on failure)
    error = resp.get("error")
    cause = resp.get("cause")
    if error:
        _section("Error Details")
        _info("error", error)
        if cause:
            try:
                cause_obj = json.loads(cause)
                print(f"\n  {_C.DIM}Cause:{_C.END}")
                print(_indent_json(cause_obj))
            except json.JSONDecodeError:
                _info("cause", cause[:1000])


def _extract_summary(out: dict[str, Any]) -> None:
    """Pull out human-readable summary fields from the execution output."""
    # Nova resolution
    nova = out.get("nova", {})
    if nova:
        _info("nova_id", nova.get("nova_id", "?"))
        _info("primary_name", nova.get("primary_name", "?"))
        if nova.get("ra_deg") is not None:
            _info("coordinates", f"({nova.get('ra_deg')}, {nova.get('dec_deg')})")

    # Ingest results
    ingest = out.get("ingest", {})
    if "rows_produced" in ingest:
        _info("photometry rows produced", ingest["rows_produced"])
        _info("photometry row failures", ingest.get("failures", 0))
    if "spectra_ingested" in ingest:
        _info("spectra ingested", ingest["spectra_ingested"])
        _info("spectra failed", ingest.get("spectra_failed", 0))

    # Finalize
    finalize = out.get("finalize", {})
    if finalize:
        outcome = finalize.get("outcome") or finalize.get("status", "?")
        _info("final outcome", outcome)

    # JobRun
    job_run = out.get("job_run", {})
    if job_run:
        _info("job_run_id", job_run.get("job_run_id", "?"))


def _indent_json(obj: Any) -> str:
    """Return indented JSON with a 4-space left margin."""
    raw = json.dumps(obj, indent=2, default=str)
    return "\n".join(f"    {line}" for line in raw.splitlines())


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Upload ticket + data files to S3 and execute the "
            "ingest_ticket Step Functions workflow."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    p.add_argument(
        "ticket_path",
        type=Path,
        help="Local path to the .txt ticket file",
    )
    p.add_argument(
        "data_dir",
        type=Path,
        help="Local directory containing data file(s) referenced by the ticket",
    )

    p.add_argument(
        "--stack",
        default="NovaCat",
        help="CloudFormation stack name (default: NovaCat; use NovaCatSmoke for smoke stack)",
    )
    p.add_argument(
        "--data-slug",
        default=None,
        help=(
            "S3 prefix slug for data files (default: derived from OBJECT NAME in ticket). "
            "Data files are uploaded to raw/data/<slug>/"
        ),
    )
    p.add_argument(
        "--correlation-id",
        default=None,
        help="Correlation ID for the workflow run (default: auto-generated UUID)",
    )
    p.add_argument(
        "--upload-only",
        action="store_true",
        help="Upload files to S3 but do NOT execute the workflow",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be uploaded and executed, but do nothing",
    )

    return p


def main() -> None:
    args = build_parser().parse_args()

    # --- Validate local paths ---
    if not args.ticket_path.exists():
        _die(f"Ticket file not found: {args.ticket_path}")
    if not args.data_dir.is_dir():
        _die(f"Data directory not found: {args.data_dir}")

    # --- Derive data slug ---
    if args.data_slug:
        data_slug = args.data_slug
    else:
        object_name = _sniff_object_name(args.ticket_path)
        if not object_name:
            _die("Could not extract OBJECT NAME from ticket file. Specify --data-slug explicitly.")
        data_slug = _slugify(object_name)
        if not data_slug:
            _die(
                f"OBJECT NAME '{object_name}' produced an empty slug. "
                "Specify --data-slug explicitly."
            )

    correlation_id = args.correlation_id or f"ingest-{data_slug}-{uuid.uuid4().hex[:8]}"

    _banner("NovaCat Ticket Ingestion")
    _info("ticket", args.ticket_path)
    _info("data_dir", args.data_dir)
    _info("data_slug", data_slug)
    _info("stack", args.stack)
    _info("correlation_id", correlation_id)
    if args.dry_run:
        _info("mode", f"{_C.YELLOW}DRY RUN{_C.END}")
    elif args.upload_only:
        _info("mode", f"{_C.CYAN}UPLOAD ONLY{_C.END}")
    else:
        _info("mode", f"{_C.GREEN}UPLOAD + EXECUTE{_C.END}")

    # --- Resolve stack ---
    _section("CloudFormation Stack")
    # The CF prefix matches the stack name for both NovaCat and NovaCatSmoke.
    cf_prefix = args.stack
    outputs = _resolve_stack_outputs(args.stack)
    bucket = _get_output(outputs, cf_prefix, "PrivateBucketName")
    sfn_arn = _get_output(outputs, cf_prefix, "IngestTicketStateMachineArn")
    _ok(f"private_bucket = {bucket}")
    _ok(f"ingest_ticket_arn = {sfn_arn.split(':')[-1]}")

    # --- Upload ---
    s3 = boto3.client("s3")
    ticket_s3_key, data_dir_prefix = _upload_files(
        s3=s3,
        bucket=bucket,
        ticket_path=args.ticket_path,
        data_dir=args.data_dir,
        data_slug=data_slug,
        dry_run=args.dry_run,
    )

    if args.upload_only:
        _banner("Upload Complete (--upload-only)")
        print("\n  To execute the workflow manually:\n")
        print("  aws stepfunctions start-sync-execution \\")
        print(f"    --state-machine-arn {sfn_arn} \\")
        payload = {
            "ticket_path": ticket_s3_key,
            "data_dir": data_dir_prefix,
            "correlation_id": correlation_id,
        }
        print(f"    --input '{json.dumps(payload)}'")
        print()
        return

    if args.dry_run:
        _section("Workflow Execution [dry-run]")
        _info("would execute", sfn_arn.split(":")[-1])
        _info("ticket_path", ticket_s3_key)
        _info("data_dir", data_dir_prefix)
        _banner("Dry Run Complete")
        return

    # --- Execute ---
    sfn_client = boto3.client("stepfunctions")
    resp = _execute_workflow(
        sfn=sfn_client,
        state_machine_arn=sfn_arn,
        ticket_s3_key=ticket_s3_key,
        data_dir_prefix=data_dir_prefix,
        correlation_id=correlation_id,
    )

    _report_result(resp)

    # --- Exit code ---
    status = resp.get("status", "")
    if status == "SUCCEEDED":
        _banner("Ingestion Complete")
    else:
        _banner(f"Ingestion {status}")
        sys.exit(1)


if __name__ == "__main__":
    main()
